'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Heart, MessageCircle, Send, Share2 } from 'lucide-react';
import type { Comment } from '@/lib/article-detail';

export function ArticleEngagement({ articleId, initialLikes, initialComments }: { articleId: string; initialLikes: number; initialComments: Comment[] }) {
  const [likes, setLikes] = useState(initialLikes); const [liked, setLiked] = useState(false); const [comments, setComments] = useState(initialComments); const [pending, setPending] = useState(false);
  const visitorId = typeof window === 'undefined' ? '' : (localStorage.getItem('noyyal-visitor') || crypto.randomUUID());
  useEffect(() => { if (visitorId) localStorage.setItem('noyyal-visitor', visitorId); }, [visitorId]);
  async function like() { if (!visitorId) return; const response = await fetch(`/api/articles/${articleId}/like`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ visitorId }) }); if (response.ok) { const data = await response.json(); setLikes(data.likes); setLiked(data.liked); } }
  async function share() { const data = { title: document.title, url: window.location.href }; if (navigator.share) await navigator.share(data); else { await navigator.clipboard.writeText(data.url); alert('Article link copied.'); } }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setPending(true); const response = await fetch(`/api/articles/${articleId}/comments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: form.get('name'), message: form.get('message') }) }); setPending(false); if (!response.ok) return alert('Unable to publish your comment.'); const comment = await response.json(); setComments((items) => [comment, ...items]); formElement.reset(); }
  return <section className="article-engagement"><div className="article-social"><button className={liked ? 'active' : ''} onClick={like}><Heart/> {likes} {likes === 1 ? 'Like' : 'Likes'}</button><a href="#comments"><MessageCircle/> {comments.length} Comments</a><button onClick={share}><Share2/> Share</button></div><div id="comments" className="comment-panel"><div><p className="article-eyebrow">JOIN THE CONVERSATION</p><h2>Comments</h2></div><form onSubmit={submit}><input name="name" maxLength={60} required placeholder="Your name"/><textarea name="message" maxLength={600} required rows={4} placeholder="Share your thoughts respectfully..."/><button disabled={pending} type="submit"><Send/> {pending ? 'POSTING...' : 'POST COMMENT'}</button></form><div className="comment-list">{comments.length ? comments.map((comment) => <article key={comment.id}><span>{comment.name.slice(0, 1).toUpperCase()}</span><div><b>{comment.name}</b><small>{new Date(comment.createdAt).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}</small><p>{comment.message}</p></div></article>) : <p className="no-comments">Be the first to share a thoughtful comment.</p>}</div></div></section>;
}
