import {BriefcaseBusiness,Camera,CloudRain,FileText,GraduationCap,MapPin,Mic,Play,Radio,ThermometerSun,TrafficCone,Upload,Video,Vote} from 'lucide-react';
import {events,localImages,tamilHeadlines} from '@/data/lowerNews';
const Img=({i=0}:{i?:number})=><img loading="lazy" src={`/images/${localImages[i%localImages.length]}`} alt="Sample local news"/>;
const Header=({title,tamil,link=true}:{title:string,tamil?:string,link?:boolean})=><div className="lower-head"><h2>{title} {tamil&&<small>{tamil}</small>}</h2>{link&&<b>VIEW ALL →</b>}</div>;
export function TrendingNews(){return <section className="lower-section"><Header title="TRENDING NOW"/><div className="trending-row">{tamilHeadlines.map((x,i)=><article className="trend-card" key={x}><strong>0{i+1}</strong><Img i={i}/><h3>{x}</h3><small>COIMBATORE　•　{i+1} hour ago</small></article>)}</div></section>}
export function CoimbatoreNews(){return <section className="lower-section"><Header title="COIMBATORE NEWS" tamil="கோவை செய்திகள்"/><div className="lower-tabs"><b>ALL</b><span>CITY</span><span>POLLACHI</span><span>METTUPALAYAM</span><span>SULUR</span><span>VALPARAI</span></div><div className="coimbatore-grid"><article className="feature-story"><Img/><div><b className="red-tag">CITY</b><h2>கோவையில் புதிய மேம்பால திட்டம் அறிவிப்பு</h2><p>நகரின் முக்கிய சாலைகளில் போக்குவரத்து நெரிசலை குறைக்கும் வகையில் புதிய திட்டங்கள் தொடங்கப்படுகின்றன.</p><small>May 19, 2026　|　10:15 AM</small><button className="red-button">READ MORE</button></div></article><div className="mini-grid">{tamilHeadlines.slice(1,5).map((x,i)=><article className="mini-story" key={x}><Img i={i+1}/><b>CITY</b><h3>{x}</h3><small>{i+1} hour ago</small></article>)}</div></div></section>}
export function CoimbatoreNow(){let data=[[CloudRain,'WEATHER','28°C','Rain Expected'],[TrafficCone,'TRAFFIC','Moderate','Avinashi Road Slow'],[Radio,'POWER','3 Areas','Scheduled Shutdown'],[Video,'TRANSPORT','Normal','Bus Services Running']];return <section className="lower-section now"><Header title="COIMBATORE NOW" link={false}/><span className="live-chip">LIVE</span><p>Live City Information</p><div className="status-grid">{data.map(([I,a,b,c])=>{let Icon=I as typeof CloudRain;return <article key={a as string}><Icon/><small>{a as string}</small><b>{b as string}</b><span>{c as string}</span></article>})}</div><h3 className="timeline-title">LIVE UPDATES</h3><div className="timeline">{['அவிநாசி சாலையில் போக்குவரத்து நெரிசல்','கோவையின் மேற்கு பகுதியில் மழைக்கு வாய்ப்பு','மின்தடை பகுதிகள் அறிவிப்பு','பேருந்து சேவை மாற்றம்'].map((x,i)=><p key={x}><b>{['10:16 AM','10:05 AM','09:48 AM','09:30 AM'][i]}</b><span>{x}</span></p>)}</div><button className="outline-button">VIEW ALL LIVE UPDATES →</button></section>}
export function FeaturedVideo(){return <section className="lower-section"><Header title="FEATURED VIDEO"/><div className="featured-video"><article className="feature-story video-feature"><Img i={3}/><div><Play/><h2>கோவை நகர வளர்ச்சி குறித்து சிறப்பு செய்தி</h2><small>COIMBATORE　•　12K views　•　08:24</small></div></article><div className="video-list">{tamilHeadlines.slice(0,4).map((x,i)=><article key={x}><div><Img i={i}/><Play/></div><p>{x}<small>LOCAL REPORT　•　03:12</small></p></article>)}</div></div></section>}
function CompactRows({items=tamilHeadlines}:{items?:string[]}){return <div className="compact-rows">{items.slice(0,5).map((x,i)=><article key={x}><Img i={i}/><div><b>NEWS</b><h3>{x}</h3><small>{i+1} hour ago</small></div></article>)}</div>}
export function TamilNaduNews(){return <section className="lower-section"><Header title="TAMIL NADU" tamil="தமிழ்நாடு"/><div className="lower-tabs"><b>LATEST</b><span>POLITICS</span><span>GOVERNMENT</span><span>EDUCATION</span></div><div className="tamilnadu"><article className="feature-story"><Img i={2}/><div><h2>தமிழகத்தில் புதிய மக்கள் நலத்திட்டங்கள் அறிவிப்பு</h2><small>CHENNAI　•　2 hours ago</small></div></article><CompactRows/></div></section>}
export function SportsEntertainment(){return <div className="dual-sections"><NewsCluster title="SPORTS" start={2}/><NewsCluster title="ENTERTAINMENT" start={4}/></div>}
function NewsCluster({title,start}:{title:string,start:number}){return <section className="lower-section cluster"><Header title={title}/><article className="cluster-main"><Img i={start}/><h2>{title==='SPORTS'?'கிரிக்கெட் போட்டிக்கு கோவையில் ரசிகர்கள் உற்சாகம்':'புதிய திரைப்படம் ரசிகர்களிடையே வரவேற்பு'}</h2></article><CompactRows items={tamilHeadlines.slice(0,3)}/></section>}
export function BusinessTechnology(){return <section className="lower-section"><Header title="BUSINESS & TECHNOLOGY"/><div className="business-row">{['கோவை தொழில் நிறுவனங்களில் AI பயன்பாடு அதிகரிப்பு','ஜவுளி துறைக்கு புதிய ஆர்டர்கள்','சிறு தொழில் முனைவோருக்கு உதவித்திட்டம்','மின்சார வாகன உற்பத்தி வளர்ச்சி','மென்பொருள் துறையில் புதிய வேலைவாய்ப்புகள்'].map((x,i)=><article key={x}><Img i={i}/><b>{i%2?'BUSINESS':'TECHNOLOGY'}</b><h3>{x}</h3><small>{i+1} hours ago</small></article>)}</div></section>}
export function PhotoStories(){return <section className="lower-section"><Header title="PHOTO STORIES" tamil="புகைப்பட செய்திகள்"/><div className="photo-gallery"><article><Img i={1}/><b>24 PHOTOS</b><h2>கோவை கோவில் திருவிழா சிறப்புப் படங்கள்</h2></article>{[0,2,3,4].map(i=><article key={i}><Img i={i}/><b>18 PHOTOS</b></article>)}</div></section>}
export function TempleEvents(){return <section className="lower-section"><Header title="TEMPLES & EVENTS" tamil="கோவில் & நிகழ்வுகள்"/><div className="event-row">{events.map((x,i)=><article key={x}><Img i={i}/><h3>{x}</h3><small><MapPin/> Coimbatore　•　Aug {18+i}</small></article>)}</div></section>}
export function JobsEducation(){return <div className="dual-sections"><section className="lower-section jobs"><Header title="JOBS & CAREERS"/>{['Software Developer','Accounts Executive','Government Apprentice','Textile Supervisor','Marketing Executive'].map((x,i)=><article key={x}><BriefcaseBusiness/><div><h3>{x}</h3><small>Coimbatore　•　Today</small></div><b>APPLY</b></article>)}</section><section className="lower-section"><Header title="EDUCATION"/><CompactRows items={['NEET தேர்வு வழிகாட்டுதல் வெளியீடு','கல்லூரி சேர்க்கை விண்ணப்பம் தொடக்கம்','பல்கலைக்கழக தேர்வு முடிவுகள்','மாணவர்களுக்கு உதவித்தொகை அறிவிப்பு','JEE பயிற்சி முகாம் கோவையில்']}/></section></div>}
export function AINewsCenter(){let items=[[Mic,'AI NEWS BULLETIN','Listen to today’s important news','LISTEN NOW'],[Play,'60 SECOND NEWS','Today’s news in one minute','PLAY'],[FileText,'TOP 10 NEWS','AI-generated daily summary','READ'],[Radio,'TAMIL AUDIO NEWS','Listen to Tamil news bulletin','LISTEN']];return <section className="lower-section ai"><Header title="AI NEWS CENTER" link={false}/><span className="ai-badge">AI POWERED</span><div>{items.map(([I,t,s,b])=>{let Icon=I as typeof Mic;return <article key={t as string}><Icon/><h3>{t as string}</h3><p>{s as string}</p><button className="outline-button">{b as string}</button></article>})}</div></section>}
export function CitizenReporter(){return <section className="citizen"><div><Camera/><h2>CITIZEN REPORTER <small>உங்கள் பகுதி செய்தியை எங்களுக்கு அனுப்புங்கள்</small></h2><p>Send local news, photos, videos or public issues to Noyyal Express.</p><small>All submissions are reviewed by our editorial team before publication.</small></div><p><button className="red-button"><Upload/> SEND NEWS</button><button className="outline-button"><Video/> UPLOAD PHOTO / VIDEO</button></p></section>}
export function DailyPoll(){return <div className="dual-sections"><section className="lower-section poll"><Header title="TODAY'S POLL" tamil="மக்கள் கருத்து" link={false}/><h3>கோவையில் எந்த பிரச்சினைக்கு உடனடி தீர்வு தேவை?</h3>{['Traffic','Roads','Water Supply','Public Transport'].map((x,i)=><p key={x}><span>{x}</span><b>{[42,28,18,12][i]}%</b><i style={{width:`${[42,28,18,12][i]}%`}}/></p>)}</section><EPaper/></div>}
export function EPaper(){return <section className="lower-section epaper"><Header title="NOYYAL EXPRESS E-PAPER" link={false}/><div><Img i={2}/><p><b>May 19, 2026</b><span>Today's complete digital newspaper</span><button className="red-button">READ E-PAPER</button><button className="outline-button">ARCHIVE</button></p></div></section>}
export function AppPromotion(){return <section className="app-promo"><div><h2>Noyyal Express – News Wherever You Go</h2><p>உங்கள் நகர செய்திகள் எப்போதும் உங்கள் கையில்</p><span>Breaking News Alerts　•　Live TV　•　Video News　•　Local Updates</span></div><p><button>▶ GOOGLE PLAY</button><button>● APP STORE</button></p></section>}
export function MegaFooter(){let cols=[['NOYYAL EXPRESS','About Us','Contact Us','Advertise With Us','Careers'],['NEWS','Coimbatore','Tamil Nadu','India','Sports','Entertainment','Business','Technology'],['LOCAL','Coimbatore City','Pollachi','Mettupalayam','Sulur','Valparai'],['SERVICES','Live TV','E-Paper','Weather','Traffic','Jobs','Citizen Reporter'],['LEGAL','Privacy Policy','Terms & Conditions','Disclaimer','Cookie Policy']];return <footer className="mega-footer"><div>{cols.map(c=><section key={c[0]}><h3>{c[0]}</h3>{c.slice(1).map(x=><a key={x}>{x}</a>)}</section>)}<section><h3>NEWSLETTER</h3><p>Get the latest news in your inbox</p><input placeholder="Enter email"/><button>SUBSCRIBE</button></section></div><p>© 2026 Noyyal Express. All Rights Reserved. <span>The Voice of Coimbatore</span></p></footer>}
