import { Pool } from 'pg';
export type Article = { id:string;title:string;slug:string;excerpt:string|null;status:'DRAFT'|'SCHEDULED'|'PUBLISHED'|'ARCHIVED';isBreaking:boolean;isTrending:boolean;views:number;publishedAt:Date|null;categoryName:string;categorySlug:string;authorName:string;imageUrl:string|null; };
type Query={page?:number;query?:string;category?:string;status?:string};
let pool:Pool|undefined;function databasePool(){if(!pool){if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is not configured.');pool=new Pool({connectionString:process.env.DATABASE_URL});}return pool;}
const select=`SELECT a.id,a.title,a.slug,a.excerpt,a.status,a."isBreaking",a."isTrending",a.views,a."publishedAt",c.name AS "categoryName",c.slug AS "categorySlug",u.name AS "authorName",m.url AS "imageUrl" FROM "Article" a JOIN "Category" c ON c.id=a."categoryId" JOIN "User" u ON u.id=a."authorId" LEFT JOIN "Media" m ON m.id=a."featuredImageId"`;
export async function getArticlePage({page=1,query='',category='',status=''}:Query={}){const where:string[]=[];const values:unknown[]=[];if(query){values.push(`%${query}%`);where.push(`a.title ILIKE $${values.length}`)}if(category){values.push(category);where.push(`c.name = $${values.length}`)}if(status){values.push(status);where.push(`a.status = $${values.length}::"ArticleStatus"`)}const condition=where.length?` WHERE ${where.join(' AND ')}`:'';const limit=10;const safePage=Math.max(1,page);const count=await databasePool().query<{count:string}>(`SELECT COUNT(*)::text AS count FROM "Article" a JOIN "Category" c ON c.id=a."categoryId"${condition}`,values);values.push(limit,(safePage-1)*limit);const rows=await databasePool().query<Article>(`${select}${condition} ORDER BY COALESCE(a."publishedAt",a."createdAt") DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);return {articles:rows.rows,total:Number(count.rows[0].count),page:safePage,limit};}
export async function getArticles(limit=20){return (await getArticlePage({page:1})).articles.slice(0,limit)}
export async function getArticleStats(){const {rows}=await databasePool().query<{status:Article['status'];count:string}>('SELECT status,COUNT(*)::text AS count FROM "Article" GROUP BY status');return rows.reduce<Record<string,number>>((stats,row)=>{stats[row.status]=Number(row.count);return stats},{})}
export type Category={id:string;name:string};export async function getCategories(){return (await databasePool().query<Category>('SELECT id,name FROM "Category" WHERE "isActive"=true ORDER BY "sortOrder",name')).rows}
export async function createArticle(input:{title:string;excerpt:string;content:string;categoryId:string;status:Article['status'];isBreaking:boolean;isTrending:boolean;scheduledAt?:string}){const id=crypto.randomUUID(),slug=`${input.title.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||'news'}-${id.slice(0,8)}`;const authors=await databasePool().query<{id:string}>('SELECT id FROM "User" WHERE "isActive"=true ORDER BY "createdAt" LIMIT 1');if(!authors.rows[0])throw new Error('An active author is required.');await databasePool().query(`INSERT INTO "Article" (id,title,slug,excerpt,content,status,"isBreaking","isTrending",views,"publishedAt","scheduledAt","updatedAt","categoryId","authorId") VALUES ($1,$2,$3,$4,$5,$6::"ArticleStatus",$7,$8,0,CASE WHEN $6::"ArticleStatus"='PUBLISHED' THEN NOW() ELSE NULL END,CASE WHEN $6::"ArticleStatus"='SCHEDULED' THEN $9::timestamp ELSE NULL END,NOW(),$10,$11)`,[id,input.title,slug,input.excerpt||null,input.content||null,input.status,input.isBreaking,input.isTrending,input.scheduledAt||null,input.categoryId,authors.rows[0].id])}